// program where the user has to guess a number generated by a program

function guessNumber() {

    // generating a random integer from 1 to 2
    const random = Math.floor(Math.random() * 2) + 1;

    // take input from the user
    let username = parseInt(prompt('What is your username ?'));
    let num1 = parseInt(prompt('Guess a number from 1 to 2: '));


    // take the input until the guess is correct,move player to stage 2
    while(num1 == random) {
        console.log("You've been awarded a point, you can now move to stage 2."); 
    }

    // Stage 2, generating a random integer from 1 to 3
    let num2 = parseInt(prompt('Guess a number from 1 to 3: '));

    if(random <= num2) {
        console.log('You guessed the correct number.');
    }
  }
// call the function
guessNumber();